"""init

Revision ID: 24344ab52589
Revises: 6210278abcb3
Create Date: 2022-03-26 18:28:33.176720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24344ab52589'
down_revision = '6210278abcb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dbo_task', 'score')
    op.drop_column('dbo_task', 'group_id')
    op.drop_column('dbo_task', 'course_id')
    op.drop_column('dbo_task', 'user_id')
    op.drop_column('dbo_task', 'code')
    op.drop_column('dbo_task', 'status')
    op.drop_column('dbo_task', 'time_start')
    op.drop_column('dbo_task', 'task_id')
    op.drop_column('dbo_task', 'time_finish')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dbo_task', sa.Column('time_finish', sa.VARCHAR(length=1), autoincrement=False, nullable=True))
    op.add_column('dbo_task', sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('dbo_task', sa.Column('time_start', sa.VARCHAR(length=19), autoincrement=False, nullable=True))
    op.add_column('dbo_task', sa.Column('status', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    op.add_column('dbo_task', sa.Column('code', sa.VARCHAR(length=57884), autoincrement=False, nullable=True))
    op.add_column('dbo_task', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('dbo_task', sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('dbo_task', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('dbo_task', sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
