"""add queue number to coureses lessons

Revision ID: 5903a07d860b
Revises: 8c0999ebbd2d
Create Date: 2022-06-16 23:34:52.152649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5903a07d860b'
down_revision = '8c0999ebbd2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dbo_courses_lessons', sa.Column('queue_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dbo_courses_lessons', 'queue_number')
    # ### end Alembic commands ###
