"""empty message

Revision ID: 8c0999ebbd2d
Revises: 560d3ae912e6
Create Date: 2022-06-09 22:38:08.427499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c0999ebbd2d'
down_revision = '560d3ae912e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dbo_lessons_tasks', sa.Column('queue_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dbo_lessons_tasks', 'queue_number')
    # ### end Alembic commands ###
