"""empty message

Revision ID: fb4f47341bf1
Revises: 24344ab52589
Create Date: 2022-06-09 22:10:28.433209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb4f47341bf1'
down_revision = '24344ab52589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE tasktype AS ENUM ('CLASS_WORK', 'HOME_WORK', 'ADDITIONAL_WORK')")
    op.add_column('dbo_courses_lessons', sa.Column('is_hidden', sa.Boolean(), nullable=True))
    op.add_column('dbo_task', sa.Column('queue_number', sa.Integer(), nullable=True))
    op.add_column('dbo_task', sa.Column('task_type', sa.Enum('CLASS_WORK', 'HOME_WORK', 'ADDITIONAL_WORK', name='tasktype'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dbo_task', 'task_type')
    op.drop_column('dbo_task', 'queue_number')
    op.drop_column('dbo_courses_lessons', 'is_hidden')
    # ### end Alembic commands ###
